### ISSUE TITLE
OrcReader?

### ISSUE THREAD

**Issue by machonky** [ddrinka/ApacheOrcDotNet#1]
Thanks for creating this library. It will be very useful for the .net community.

Is there an OrcReader in the works?

**Comment by ddrinka** [comment]
@machonky The datastructures all exist for reading and writing--the test cases already round-trip data.  But there's not a unified interface to reading that data yet, and the writer interface needs to change as well.  This is a project I'll be coming back to in a few months, and a reader is definitely on the docket.

**Comment by flo8** [comment]
Hi, great to see an ORC library for C# thanks for creating it! are you still working on this?

**Comment by ddrinka** [comment]
@flo8, This is still a project I'd like to complete, but for the time being we've found that using JSON with tools like Presto/Hive has worked well enough to satisfy our immediate needs.  We convert to ORC as quickly as possible, but for data ingest, batching out to JSON fits our pipeline well.

I've also been seeing enough progress with the native C++ reader/writer that it may end up making more sense creating .net bindings to a cross-platform C++ build of the ORC libraries, rather than continuing to develop a managed version.  Thoughts on this approach?

**Comment by flo8** [comment]
@ddrinka Yes the idea of using cross-platform of the C++ ORC libraries is a good idea I didn't think about. Clearly that might be a much better time investment rather than rewriting everything.
